### ISSUE TITLE
Trying for Raspberry Pi 3 Model B Rev 1.2

### ISSUE THREAD

**Issue by Mazuco** [kgbplus/gpiotest#6]
root@automacao:~/gpiotest# python gpiotest.py 
hardware not supported
Traceback (most recent call last):
  File "gpiotest.py", line 406, in <module>
    termOn()
  File "gpiotest.py", line 39, in termOn
    curses.nocbreak()
_curses.error: must call initscr() first

**Comment by RomanMindlin** [comment]
Please, try to pull (update) new version
